# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

steps:

- task: UseDotNet@2
  displayName: 'Use .NET SDK'
  inputs:
    version: 10.0.x

- script: dotnet test --configuration Release
  displayName: 'Run Unit Tests'

- script: |
    VERSION=$(sed -n 's/.*<Version>\(.*\)<\/Version>.*/\1/p' build/SharedVersion.props | xargs)
    if [[ "$(Build.SourceBranch)" == refs/heads/release/* || "$(Build.SourceBranch)" == refs/heads/master ]]; then
      dotnet pack src/Avalonia.Controls.TreeDataGrid/Avalonia.Controls.TreeDataGrid.csproj --configuration Release /p:Version="$VERSION"
    else
      BUILD_ID_PADDED=$(printf "%07d" $(Build.BuildId))
      dotnet pack src/Avalonia.Controls.TreeDataGrid/Avalonia.Controls.TreeDataGrid.csproj --configuration Release /p:Version="${VERSION}-cibuild${BUILD_ID_PADDED}-beta"
    fi
  displayName: 'Generate Nuget Package'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/src/Avalonia.Controls.TreeDataGrid/bin/Release/'
    ArtifactName: 'drop'
    publishLocation: 'Container'
